# =============================================================================
# example3_before_ae_table_rtables.R
#
# THE "BEFORE" STATE for Example 3 (toolchain translation).
#
# A treatment-emergent adverse event (TEAE) summary table -- n (%) of
# subjects with each Preferred Term, by treatment arm, safety population --
# built with the classic {rtables} layout engine.
#
# In the live demo, students already have this script open and working.
# The prompt asks Posit Assistant to rebuild the SAME table using the
# ARD-based {cards} + {tfrmt} approach instead (see the walkthrough guide).
#
# Data: real pharmaverse test data (adae_prod.csv / adsl_small.csv),
# generated by 00_build_data_artifacts.R from {pharmaverseadam}.
# =============================================================================

suppressMessages({
  library(rtables)
  library(dplyr)
})

adae <- read.csv("../03_reference_adam/adae_prod.csv", stringsAsFactors = FALSE)
adsl <- read.csv("../03_reference_adam/adsl_small.csv", stringsAsFactors = FALSE)

arms <- adsl %>% filter(SAFFL == "Y") %>% count(TRT01A, name = "N") %>% arrange(TRT01A)

teae <- adae %>%
  filter(TRTEMFL == "Y", SAFFL == "Y") %>%
  distinct(USUBJID, AEDECOD, TRT01A)

# Top 8 most frequent preferred terms overall, for a compact demo table
top_terms <- teae %>% count(AEDECOD, name = "n_subj") %>% arrange(desc(n_subj)) %>% head(8) %>% pull(AEDECOD)

counts <- teae %>%
  filter(AEDECOD %in% top_terms) %>%
  count(AEDECOD, TRT01A, name = "n") %>%
  tidyr::complete(AEDECOD = top_terms, TRT01A = arms$TRT01A, fill = list(n = 0)) %>%
  left_join(arms, by = "TRT01A") %>%
  mutate(pct = 100 * n / N)

fmt_cell <- function(n, pct) sprintf("%d (%.1f%%)", n, pct)

# Build the rtables object row by row: one rrow() per Preferred Term
mk_row <- function(term) {
  vals <- counts %>% filter(AEDECOD == term) %>% arrange(TRT01A)
  rrow(term,
       fmt_cell(vals$n[1], vals$pct[1]),
       fmt_cell(vals$n[2], vals$pct[2]),
       fmt_cell(vals$n[3], vals$pct[3]))
}

hdr <- rheader(
  rrow("", paste0(arms$TRT01A[1], " (N=", arms$N[1], ")"),
           paste0(arms$TRT01A[2], " (N=", arms$N[2], ")"),
           paste0(arms$TRT01A[3], " (N=", arms$N[3], ")"))
)

result <- rtable(
  header = hdr,
  rrows = lapply(top_terms, mk_row)
)

cat("---- Rendered table (ASCII) ----\n")
print(result)
